# Generated by Django 5.1.6 on 2025-02-21 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('payment_type', models.CharField(blank=True, choices=[('subscription', 'Subscription'), ('renewal', 'Renewal')], default='subscription', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20, null=True)),
                ('amount', models.BigIntegerField(blank=True, help_text='payment amount in kobo', null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
