# Generated by Django 5.1.6 on 2025-02-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_timedauthtokenpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_send_message', 'Can send message'), ('can_view_chat', 'Can view chats'), ('can_edit_message', 'Can edit message')]},
        ),
    ]
