# Generated by Django 5.1.6 on 2025-02-21 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('service_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('service_user_logout_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
