# Generated by Django 5.1.6 on 2025-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_serviceapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapikey',
            name='issuer_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
